### ISSUE TITLE
Discussion about Device and Mandatory Fields

### ISSUE THREAD

**Issue by hhslepicka** [pcdshub/happi#106]
## Expected Behavior
Since other labs are looking into Happi, should we make Device be completely flexible with additional metadata and create the PCDSDevice or some other name that will have mandatory fields such as `functional_group` and `location_group` ?

## Current Behavior
Device requires `functional_group` and `location_group` along with some other information that is a bit LCLS specific.

## Possible Solution
Create a new type of container that is the PCDS basic Device and make Device very relaxed.

**Comment by hhslepicka** [comment]
From SLACK talk:
- Zach says: "My answer is yes"
- Ken says: 👍

**Comment by ZLLentz** [comment]
I think we should use this opportunity to change our semantics too. These should never have been called `Device` because of the conflict with `ophyd`. I think `HappiItem` should be the super basic entry, then if you want an ophyd device entry it should be `DeviceItem`, and then more specific should be `SlitsItem`, etc. if we want these.

I would also advocate for pulling all SLAC-specific assumptions out of `happi` and into e.g. `happi_lcls`

**Comment by ZLLentz** [comment]
There would also need to be a way to register your site-specific classes with `happi`

**Comment by klauer** [comment]
Not that I'm against it necessarily, I think pulling things out into a separate package for PCDS/LCLS is probably slightly overkill at this point.

A minimum viable thing to make this useful for others and still keep PCDS stuff our priority would be refactoring as @hhslepicka suggests, I think.

**Comment by hhslepicka** [comment]
Discussion from #112:

> The container discovery will need most of the refactor.(https://github.com/pcdshub/happi/blob/master/happi/client.py#L44-L52)
> 
> Here is one idea:
> Make containers be converted from a python file to a namespace package (https://packaging.python.org/guides/packaging-namespace-packages/#creating-a-namespace-package) with a registry inside of it.
> Facilities that wants to add new containers can create a package which will share this namespace and be discovered by Happi when running.
> 
> Another idea (by @klauer):
> Investigate the usage of entry_points so that we don't need to enforce a package architecture into projects that want to extend the containers for Happi.
