### ISSUE TITLE
Deprecate "device" verbiage for classes from Happi

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/happi#124]
Use `item` instead of `device` to clarify which things are actual functioning devices and which things are descriptions of functioning devices

Todo:
- [x] Deprecate `Device` class, replace with `OphydItem` and `LCLSItem`
- [x] Deprecate `device` module, replace with `item`
- [x] Deprecate methods with `device` in the name except where they return a user's instance, replace with `item`
- [x] Adjust comments, docstrings, and internal code to clarify types
- [x] Clean up the docs in general
- [x] In deprecated classes, ensure documentation refers to replacement class (per @ZryletTC https://github.com/pcdshub/happi/pull/193#discussion_r552331896)

Related:
- [x] Move `LCLSItem` and LCLS's containers into `pcdsdevices`

**Comment by ZLLentz** [comment]
Started in #122

**Comment by klauer** [comment]
- [x] `SearchResult.item`, `Client.all_items` and deprecate `SearchResult.device`, `Client.all_devices`

**Comment by ZLLentz** [comment]
I'm currently getting a headache trying to read through the Client docstrings- it uses device, instantiated device, item, etc. seemingly interchangeably.

**Comment by klauer** [comment]
It's slowly improving but still bad, for sure. Wish we had gotten rid of 'device' longer ago.
