### ISSUE TITLE
CLI `happi search` does not work with capitalized component names

### ISSUE THREAD

**Issue by rajanplumley** [pcdshub/happi#144]
`happi search AT2L0` does not return anything but `happi search at2l0` works as expected
## Expected Behavior
`happi search AT2L0` should return the object for AT2L0

## Current Behavior
it currently differentiates between capitalized and non-capitalized names. 

## Possible Solution
pass the arg string into a `<string>.lower()`

## Steps to Reproduce (for bugs)
![image](https://user-images.githubusercontent.com/25809004/83684530-096f6d00-a59c-11ea-8d7e-e18445961e51.png)

**Comment by ZLLentz** [comment]
We should extend this to other fields too, like beamline and stand.
