### ISSUE TITLE
Get metadata by attribute

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/happi#15]
Implement custom `getattribute` to grab information from the `extraneous` dictionary

**Comment by teddyrendahl** [comment]
Want to avoid messing with `setattr` on Device. Not obvious how necessary this is if we restructure devices. Messing with `getattr` does one half of the equation but leaves a confusing situation for the operator. Requires more thought than originally expected..

**Comment by klauer** [comment]
This was refactored to instead be `__getitem__` and also allows for easy dict-ification and iterability of `HappiItem`s.
