### ISSUE TITLE
example db.json cannot be validated

### ISSUE THREAD

**Issue by JulReinhardt** [pcdshub/happi#150]
## Expected Behavior
After loading the example/db.json as a client and running client.validate() nothing should be returned if all devices are properly described.

## Current Behavior
```
In [24]: client = happi.Client(path='./happi/examples/db.json')

In [25]: client.validate()
Failed to validate tv1l0_vgc_1 because The information relating to the device class has been modified to the point where the object can not be initialized, please load the corresponding document
Failed to validate tv1l0_vgc_2 because The information relating to the device class has been modified to the point where the object can not be initialized, please load the corresponding document
Out[25]: ['tv1l0_vgc_1', 'tv1l0_vgc_2']
```

## Possible Solution
Providing a new valid example file for new users of happi, so that they can better understand what is required to build a valid database file

## Environment
Mac OS Catalina 10.15.5
conda environment, 
python 3.8, 
happi 1.6.1, 
ipython 7.16.1,
pymongo 3.10.1
mongomock 3.19.0
matplotlib 3.2.2

**Comment by hhslepicka** [comment]
This happens from our migration of the LCLS specific containers from Happi to `pcdsdevices`. The example must be reworked to use `OphydItem` instead and be standalone.
