### ISSUE TITLE
`happi` without any sub-commands outputs nothing

### ISSUE THREAD

**Issue by klauer** [pcdshub/happi#154]
## Current Behavior

Typing `happi` with no sub-commands outputs nothing:
```bash
$ happi
$
```

## Expected Behavior
It should output, say, the help information:

```
$ happi
usage: happi [-h] [--path PATH] [--verbose] [--version]
             {search,add,edit,load} ...
```

**Comment by surajduncan** [comment]
I would like to solve this issue

**Comment by klauer** [comment]
@surajduncan, we welcome your PRs.
