### ISSUE TITLE
Lack of some coverage/tests for CLI

### ISSUE THREAD

**Issue by cristinasewell** [pcdshub/happi#162]
## Expected Behavior

Some testing for the `add`, `clone`, `edit`, `load` commands would be great.

## Current Behavior

Currently those commands are not tested 
## Possible Solution

https://github.com/pcdshub/happi/pull/161#issuecomment-676606588
## Context

 This would allow programmers to refactor code and make sure the module still works correctly.

**Comment by ZLLentz** [comment]
This is probably my mistake, we were in a rush to get these out and never revisited them for testing.

**Comment by cristinasewell** [comment]
@ZLLentz  can I try to work on this Issue?

**Comment by ZLLentz** [comment]
I would be very :+1: on filling the testing gaps, especially here in CLI, a very common user codepath
