### ISSUE TITLE
JSON load failure "expecting property name enclosed in double quotes"

### ISSUE THREAD

**Issue by klauer** [pcdshub/happi#167]
![image](https://user-images.githubusercontent.com/5139267/92156355-b0eb7e00-eddd-11ea-943b-87fa5aca6b0d.png)

Guesses:
* There may have been a write in process
* NFS may have given out while reading it

Should happi json backend retry loading in the event of a syntax error?

**Comment by ZLLentz** [comment]
Should happi json backend open the file and show us line 3977 in cases like this?

**Comment by klauer** [comment]
It looks like just bad timing, unless someone was really editing the JSON directly:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/5139267/92161460-843b6480-ede5-11ea-89af-83d5aed4c4e4.png">

Showing where the bad line is would help developers, but making another attempt to load the file could help users. 🤷‍♂️

**Comment by ZLLentz** [comment]
Try three times, then show the line?

I agree the saving could be safer. We also may be getting closer to wanting split files for different areas.

**Comment by ZryletTC** [comment]
Sorry, that was me

> It looks like just bad timing, unless someone was really editing the JSON directly

Both, bad timing as I was writing to it directly and introduced a bug for like five minutes.

> Should happi json backend open the file and show us line 3977 in cases like this?

Yes, please :)

> but making another attempt to load the file could help users

Also yes please :)

**Comment by klauer** [comment]
Since we identified that it wasn't happi writing the file or failing to read it, this issue isn't exactly valid.

However, other good discussions regarding the root cause of this and maybe potential paths forward are popping up (#165, #169, among others).
