### ISSUE TITLE
CLI tools: update, dump

### ISSUE THREAD

**Issue by untzag** [pcdshub/happi#190]
## Expected Behavior

It would be great for me if the happi CLI supported richer ways for external applications to interact with the database. These are intended as an API, not necessarily a tool for humans.

## Current Behavior

N/A

## Possible Solution

I would love to see happi support the following:

```bash
$ happi update <json>
```

Here, applications would feed happi a JSON-formatted version of the database contents. Happi would add these new items to the database. Any items that already exist would be overwritten with the new values. Just like `dict.update` in Python. Happi should verify items are formatted correctly before committing to the database.

```bash
$ happi dump
<json to standard out>
```

Literally just dump the whole database as a JSON string to standard out. The output of dump should be able to transparently pipe into update---in this way it will become easy to concatenate databases.

## Steps to Reproduce (for bugs)

N/A

## Context

I'm trying to use happi to manage [yaq](https://yaq.fyi) devices. In yaq-land, I already have tooling that allows me to see what's installed. All I need to do is reformat this information and dump it into happi. Since yaq is not necessarily Python, I'd prefer to do this through an entry point rather than the Python API.

## Your Environment

N/A

**Comment by klauer** [comment]
`happi update` would be great. :+1:
`happi dump` sorta already exists: `happi search '*' --json`

I'm personally very much in favor of making more of happi's CLI tooling JSON-friendly.
