### ISSUE TITLE
HappiItem rejects names under three charachters

### ISSUE THREAD

**Issue by untzag** [pcdshub/happi#206]
## Expected Behavior

I commonly call my devices simple things like `d1` or `wa`. I was surprised to find that the HappiItem baseclass rejects these names. Your regex for name, `[a-z][a-z\_0-9]{2,78}$`, requires at least 3 characters.

## Current Behavior

Is enforcing at least 3 characters necessary? I would have expected that any valid Python identifier would be a valid HappiItem name.

Since we're talking about it, you're also enforcing lower case... is that necessary?

## Possible Solution

 `[a-z][a-z\_0-9]{0,78}$`

I also understand that I can change this behavior within my `YAQItem` subclass, and am happy to do that instead if maintainers wish to keep these restraints for the base class.

**Comment by klauer** [comment]
For our purposes, the happi database holds a huge number of items and is shared among many different hutches/beamlines. Choosing a one or two character name will only serve to cause confusion or potential for clashing names. For our users who insist that typing more than 2 characters is just _too many_, we suggest they configure aliases in their beamline-specific startup scripts.

This may be something we have to revisit, as not all facilities (or users such as yourself) will have the same constraints. Naming requirements should be facility-specified and not forced on you by happi.

That said, I think we can all agree that at minimum `name.isidentifier()` should be `True`.

**Comment by untzag** [comment]
Y'all already raise an exception if a user accidentally tries to overwrite an existing `_id`.

**Comment by klauer** [comment]
> Y'all already raise an exception if a user accidentally tries to overwrite an existing _id.

Indeed, we do. "First come, first serve" sadly is insufficient for facility naming standards.

**Comment by untzag** [comment]
That makes sense. Perhaps y'all could be permissive by default but respect an environment variable to lock down name options when appropriate.

**Comment by ZLLentz** [comment]
I think it would be ok to open up the tight restrictions of the `name` entry on `HappiItem`. LCLS can easily restrict the database names in our site-specific containers, as can any other site that wants to go that way for the reasons @klauer explained above. Another option is to include a tightly-restricted `OphydItem` subclass here with some "common restrictions" on names, etc., but I'm not sure how useful that is.
