### ISSUE TITLE
Docs Link Redirect Error

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/happi#210]
## Expected Behavior

https://pcdshub.github.io/happi should show the docs

## Current Behavior

https://pcdshub.github.io/happi redirects to a 404
https://pcdshub.github.io/happi/master shows the docs

As a temporary thing, I've changed the website docs link to the one that works

**Comment by klauer** [comment]
Like minds... (#208)

**Comment by ZLLentz** [comment]
Whoops!
Closing as a duplicate
