### ISSUE TITLE
Remove fcntl warning

### ISSUE THREAD

**Issue by klauer** [pcdshub/happi#220]
The following message on Windows is annoying:

https://github.com/pcdshub/happi/blob/d5cba946cd4a58a0b6a9da011e256f84d9ced81a/happi/backends/json_db.py#L22

This is something that should be part of the documentation, not a message on every invocation of `happi`.

**Comment by klauer** [comment]
Remove backend unavailable warnings, too?

**Comment by JulReinhardt** [comment]
I agree that the fcntl warning is not necessary. You want to remove backend warnings, like when json or mongo packages are not properly installed?

**Comment by klauer** [comment]
Yes, @JulReinhardt, I think it should only be an error if you actually try to _use_ those backends when they are unavailable. Seem reasonable?

**Comment by JulReinhardt** [comment]
Yes, agreed.
