### ISSUE TITLE
Happi GUI Front-end tools (Qt and/or web-based)

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/happi#221]
## Expected Behavior

Develop a GUI that lets you browse and edit the happi database

**Comment by klauer** [comment]
Web-based or PyQt-based are our top options.

**Comment by ZLLentz** [comment]
Web-based:
- happi server process (with some web auth?)
- web front-end that communicates with the process

PyQt-based:
- local application that runs qt and happi
- auth is based on being able to log in to the system

**Comment by klauer** [comment]
Some browsing support is available already:
https://github.com/pcdshub/happi/blob/master/happi/qt/model.py

atef improves upon this with a happi item + device/component browser. Some of this should be upstreamed to happi:

![image](https://user-images.githubusercontent.com/5139267/167188494-bf2815c4-f1d4-4205-9baf-382bb7c940ad.png)

**Comment by tangkong** [comment]
Should we close this and make more specific issues?  top of mind thanks to #246 
- a web gui might not be absurd once we properly switch to mongo
- editable via gui might be in striking distance after merging in atef changes

**Comment by klauer** [comment]
Sounds good to me 👍
