### ISSUE TITLE
CI Docs failing to build

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/happi#224]
## Current Behavior

```
Warning, treated as error:
/home/travis/build/pcdshub/happi/docs/source/client.rst:33:more than one target found for 'any' cross-reference 'Client': could be :py:class:`happi.Client` or :py:class:`happi.client.Client`
Makefile:24: recipe for target 'html' failed
make: *** [html] Error 2
```

**Comment by ZryletTC** [comment]
This is an easy fix but seems to have been triggered by using the new version of sphinx. Sphinx 4.1.2 shows this warning/error but version 3.5.4 succeeds without any warnings. I don't see anything in their changelog that would explain this but they must've made it stricter about ambiguous cross-reference targets somewhere.

**Comment by ZryletTC** [comment]
If you agree, I'm gonna stop digging into where in their code it became stricter and just make the fix in our code.

**Comment by ZLLentz** [comment]
Fixing our docs or forcing sphinx to the old version are both acceptable solutions
