### ISSUE TITLE
Fallback of standard Python REPL for optional IPython dependency

### ISSUE THREAD

**Issue by klauer** [pcdshub/happi#259]
## Issue

IPython is optional, but `happi load` will fail here without it:

https://github.com/pcdshub/happi/blob/ffdf677d5b4a81824c05bc067ff26a6322e42654/happi/cli.py#L320

## Suggested fix

Support the standard IPython REPL when IPython is unavailable

**Comment by ZLLentz** [comment]
Saving this for later
https://stackoverflow.com/questions/5597836/embed-create-an-interactive-python-shell-inside-a-python-program
