### ISSUE TITLE
CLI API break: --json is now --show_json

### ISSUE THREAD

**Issue by klauer** [pcdshub/happi#288]
## Code

https://github.com/pcdshub/happi/blob/dc37705ab2ae93fc2f88bd67f5a771e7f80c8a28/happi/cli.py#L77

## Issue

This was `--json` and now it's `--show_json` without proper deprecation of the original

Separately, if "show json" is deemed preferable, this should probably be `--show-json` to be more CLI-friendly.

**Comment by tangkong** [comment]
Restoring `--json` in addition to `--show_json` is easy enough, I can lump that into the audit PR.

**Comment by tangkong** [comment]
closed by #286
