### ISSUE TITLE
Pre-release notes script does not check if EDITOR is unset

### ISSUE THREAD

**Issue by klauer** [pcdshub/happi#326]
## Issue

This code in the pre-release notes script:
https://github.com/pcdshub/happi/blob/42aecf8504134bbc8d2f576c796c0a261df3f1f9/docs/pre-release-notes.sh#L32

Assumes `EDITOR` is set
And if `EDITOR` is unset, it tries to _run_ the newly-created `.rst` file (oops!)
It should warn, default to `vi` (totally unbiased), or do nothing/exit early

## Context

@laura-king ran into this while we were showing her the script

**Comment by tangkong** [comment]
This is probably a issue for every prerelease notes script... I've just been copying it over every time I see it missing.

**Comment by tangkong** [comment]
Really the place to change this would be in our cookiecutter.   After that we should change existing repos
https://github.com/pcdshub/cookiecutter-pcds-python/blob/master/%7B%7B%20cookiecutter.folder_name%20%7D%7D/docs/pre-release-notes.sh
