### ISSUE TITLE
ENH: help `happi audit` pipe / redirect / write to a file

### ISSUE THREAD

**Issue by tangkong** [pcdshub/happi#338]
## Expected Behavior
We should be able to save audit results to a file easily

## Current Behavior
Currently we output a table with audit failures, which maybe isn't the best for dumping to a file that you might want to use for programmatic tasks. 

### A couple reasons why `happi audit '*' > audit_output.txt` is awful:

We also print a progress ticker (x/N entries audited...), which uses a [carriage return](https://github.com/pcdshub/happi/blob/2659bdb6214916a28218305a70cbfcc1547ddcdd/happi/audit.py#L269).  This renders each line in the redirected output.  

The table also fails to write to a file nicely, since the [table width is unset ](https://github.com/pcdshub/happi/blob/2659bdb6214916a28218305a70cbfcc1547ddcdd/happi/cli.py#L1093-L1095)in non-interactive mode.

## Possible Solution
Maybe it's best to just have a `--file-out` flag or something similar where we write a csv with all the audit results

## Context
I had a task to run a `happi audit` periodically, I did so and there was pain

## Your Environment
pcds-5.7.3, happi-2.4.0

**Comment by klauer** [comment]
You can detect whether or not the terminal is interactive
`sys.__stdin__.isatty()`
